version: "3"
services:

  sitedb:
    container_name: site-database
    environment:
      - PGDATA
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: postgres:12
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - /usr/site/data/pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:latest
    restart: "no"
    container_name: redis-site
    environment:
      - REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - /usr/site/conf/redis.conf:/etc/redis/redis.conf
      - /usr/site/data/redis:/data
    command: redis-server /etc/redis/redis.conf --requirepass werido
    # command: redis-server --requirepass werido
    privileged: true

  django:
    container_name: site-backend
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - REDIS_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - EMAIL_PWD
    build: 
      context: ../werido-site-backend
      dockerfile: Dockerfile
    command:       
      - /bin/bash
      - -c
      - |
        supervisord  -c celery.conf
        python manage.py makemigrations
        python manage.py migrate
        gunicorn -c gunicorn.py core.asgi:application
    volumes:
      - /pythons/blogNew/werido-site-backend/:/var/www/html/weridoBlog/
    ports:
      - "8000:8000"
      - "465:465"
      - "25:25"
    depends_on:
      - sitedb
      - redis
  
  # celery:
  #   image: celery-with-docker-compose:latest
  #   # build: .
  #   container_name: celery-backend
  #   environment:
  #     - POSTGRES_HOST
  #     - POSTGRES_PORT
  #     - REDIS_PASSWORD
  #     - REDIS_HOST
  #     - REDIS_PORT
  #   command:       
  #     - /bin/bash
  #     - -c
  #     - |
  #       celery -A core worker -l info
  #   volumes:
  #     - /pythons/blogNew/werido-site-backend/:/deploy/app
  #   depends_on:
  #     - django  
  #     - redis  

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - /usr/rabbitmq:/etc/rabbitmq/enabled_plugins


  front:
    # 前端先打包
    container_name: site-front
    image: nginx
    ports:
    - 80:80
    restart: unless-stopped
    volumes:
    - /pythons/site-new/dist:/usr/share/nginx/html/
    - /pythons/nginx/conf.d/:/etc/nginx/conf.d/ 
    - /pythons/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /usr/site/logs/nginx/:/var/log/nginx/
    depends_on:
    - django

volumes:
  pgdata: